const { useState, useEffect, useRef, useCallback } = React;

function App() {
    // 1. Declarative React State
    const [image, setImage] = useState(null);
    const [blobUrl, setBlobUrl] = useState(null);
    const [aspectRatio, setAspectRatio] = useState('original');
    const [panX, setPanX] = useState(0.5);
    const [panY, setPanY] = useState(0.5);
    const [flipH, setFlipH] = useState(false);
    const [flipV, setFlipV] = useState(false);
    const [rotation, setRotation] = useState(0);
    const [statusText, setStatusText] = useState('Ready (Supports Apple HEIC)');
    const [containerSize, setContainerSize] = useState({ width: 0, height: 0 });

    // Refs to bridge with Vanilla DOM/Core
    const canvasRef = useRef(null);
    const engineRef = useRef(null);
    const containerRef = useRef(null);
    const fileInputRef = useRef(null);
    const mathRef = useRef(null); // Stores the pure math boundaries generated by Core

    // Initialize Vanilla Engine once Canvas mounts
    useEffect(() => {
        if (canvasRef.current && !engineRef.current) {
            engineRef.current = new window.CanvasEngine(canvasRef.current);
        }
    }, []);

    // Add a ResizeObserver to watch the container and update its size in state.
    useEffect(() => {
        const resizeObserver = new ResizeObserver(entries => {
            if (entries && entries.length > 0) {
                // Use integer values to prevent excessive re-renders from sub-pixel changes.
                const { width, height } = entries[0].contentRect;
                setContainerSize({ width: Math.floor(width), height: Math.floor(height) });
            }
        });

        const el = containerRef.current;
        if (el) {
            resizeObserver.observe(el);
        }

        return () => {
            if (el) {
                resizeObserver.unobserve(el);
            }
        };
    }, []);

    // Re-render Vanilla Engine whenever React state updates
    useEffect(() => {
        if (engineRef.current && containerSize.width > 0) {
            const engineState = { image, aspectRatio, panX, panY, flipH, flipV, rotation };
            mathRef.current = engineRef.current.render(engineState, containerSize.width, containerSize.height);
        }
    }, [image, aspectRatio, panX, panY, flipH, flipV, rotation, containerSize]);

    // 2. Ingestion Engine Handler
    const loadIntoState = (blob, fileName) => {
        if (blobUrl) URL.revokeObjectURL(blobUrl); // Memory clean
        const url = URL.createObjectURL(blob);
        setBlobUrl(url);

        const img = new Image();
        img.onload = () => {
            setImage(img);
            setAspectRatio('original');
            setPanX(0.5); setPanY(0.5);
            setFlipH(false); setFlipV(false); setRotation(0);
            setStatusText(`Active File: ${fileName}`);
        };
        img.src = url;
    };

    const handleFileChange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        
        const isHeic = file.name.toLowerCase().match(/\.(heic|heif)$/);
        setStatusText('Processing (Offloading HEIC...)');

        if (isHeic) {
            const worker = new Worker('js/heic-worker.js');
            worker.postMessage(file);
            worker.onmessage = (e) => {
                if (e.data.success) loadIntoState(e.data.blob, file.name);
                else setStatusText(`Sys Error: ${e.data.error}`);
                worker.terminate();
            };
        } else {
            loadIntoState(file, file.name);
        }
    };

    // 3. Mouse Panning Logic
    const dragInfo = useRef({ active: false, startX: 0, startY: 0, initialPanX: 0, initialPanY: 0 });

    const handleMouseDown = (e) => {
        e.preventDefault();
        if (!image) return;
        dragInfo.current = { active: true, startX: e.clientX, startY: e.clientY, initialPanX: panX, initialPanY: panY };
    };

    const handleMouseMove = useCallback((e) => {
        if (!dragInfo.current.active || !mathRef.current || !canvasRef.current) return;

        const rect = canvasRef.current.getBoundingClientRect();
        const math = mathRef.current;

        const scaleX = canvasRef.current.width / rect.width;
        const scaleY = canvasRef.current.height / rect.height;
        const deltaLogicalX = (e.clientX - dragInfo.current.startX) * scaleX;
        const deltaLogicalY = (e.clientY - dragInfo.current.startY) * scaleY;

        if (math.maxOffsetX > 0) setPanX(Math.max(0, Math.min(1, dragInfo.current.initialPanX - (deltaLogicalX / math.maxOffsetX))));
        if (math.maxOffsetY > 0) setPanY(Math.max(0, Math.min(1, dragInfo.current.initialPanY - (deltaLogicalY / math.maxOffsetY))));
    }, []); 

    useEffect(() => {
        const stopDrag = () => { dragInfo.current.active = false; };
        window.addEventListener('mousemove', handleMouseMove);
        window.addEventListener('mouseup', stopDrag);
        return () => {
            window.removeEventListener('mousemove', handleMouseMove);
            window.removeEventListener('mouseup', stopDrag);
        };
    }, [handleMouseMove]);

    // 4. Declarative UI Component
    return (
        <div className="editor-layout">
            <aside className="sidebar">
                <div className="panel-section">
                    <h2>1. Core Ingestion Engine</h2>
                    <button className="btn" onClick={() => fileInputRef.current.click()}>Upload Image</button>
                    <input type="file" ref={fileInputRef} accept="image/*,.heic,.heif" hidden onChange={handleFileChange} />
                    <div className="status-indicator">{statusText}</div>
                </div>

                <div className="panel-section">
                    <h2>2. Math / Pan Constraints</h2>
                    <label>Target Aspect Ratio</label>
                    <select value={aspectRatio} onChange={e => setAspectRatio(e.target.value)}>
                        <option value="original">Original Aspect Ratio</option>
                        <optgroup label="Social Media & Video">
                            <option value="16/9">16:9 (YouTube / Widescreen)</option>
                            <option value="9/16">9:16 (Shorts / Story)</option>
                            <option value="1/1">1:1 (Square / IG Post)</option>
                            <option value="4/5">4:5 (IG Portrait)</option>
                            <option value="5/4">5:4 (FB/Twitter Landscape)</option>
                            <option value="4/3">4:3 (Standard TV / iPad)</option>
                            <option value="3/4">3:4 (Pinterest Portrait)</option>
                            <option value="21/9">21:9 (Ultrawide Cinematic)</option>
                        </optgroup>
                        <optgroup label="Standard Print (R-Series)">
                            <option value="3/2">3:2 (4R 6x4" Landscape)</option>
                            <option value="2/3">2:3 (4R 4x6" Portrait)</option>
                            <option value="7/5">7:5 (5R 7x5" Landscape)</option>
                            <option value="5/7">5:7 (5R 5x7" Portrait)</option>
                            <option value="8/6">4:3 (6R 8x6" Landscape)</option>
                            <option value="6/8">3:4 (6R 6x8" Portrait)</option>
                            <option value="10/8">5:4 (8R 10x8" Landscape)</option>
                            <option value="8/10">4:5 (8R 8x10" Portrait)</option>
                            <option value="14/11">14:11 (11R 14x11" Landscape)</option>
                            <option value="11/14">11:14 (11R 11x14" Portrait)</option>
                        </optgroup>
                        <optgroup label="Documents">
                            <option value="1/1.414">A4 Portrait</option>
                            <option value="1.414/1">A4 Landscape</option>
                            <option value="8.5/11">US Letter Portrait</option>
                            <option value="11/8.5">US Letter Landscape</option>
                        </optgroup>
                    </select>
                    
                    <label>Pan Offset X</label>
                    <input type="range" min="0" max="1" step="0.001" value={panX} onChange={e => setPanX(parseFloat(e.target.value))} />
                    
                    <label>Pan Offset Y</label>
                    <input type="range" min="0" max="1" step="0.001" value={panY} onChange={e => setPanY(parseFloat(e.target.value))} />
                </div>

                <div className="panel-section">
                    <h2>3. Matrix Transforms</h2>
                    <label>Non-Destructive Canvas</label>
                    <div className="btn-group">
                        <button className="btn" onClick={() => setFlipH(!flipH)}>Flip H</button>
                        <button className="btn" onClick={() => setFlipV(!flipV)}>Flip V</button>
                        <button className="btn" onClick={() => setRotation((rotation + 90) % 360)}>Rot 90°</button>
                    </div>
                </div>
            </aside>

            <main className="workspace">
                <div className="canvas-container">
                    <canvas ref={canvasRef} onMouseDown={handleMouseDown}></canvas>
                </div>
            </main>
        </div>
    );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);